% Method to transform a calStruct generated by @Calibrator to a calStruct
% with the old-style format (expected by old-style calibration routines).
%
% Usage:
% oldFormatCalStruct = Calibrator.calStructWithOldFormat(newFormatCalStruct);
% 
% 4/16/2014   npc   Wrote it.
%

function oldFormatCalStruct = calStructWithOldFormat(obj, newFormatCalStruct)
% oldFormatCalStruct = calStructWithOldFormat(newFormatCalStruct)
%
% Description:
% Method to transform a calStruct generated by @Calibrator to a calStruct
% with the old-style format.
%
% Output:
% calStruct - A cal struct compatible with that expected 

    oldFormatCalStruct = OldFormatCalStructFromNewFormatCalStruct(newFormatCalStruct);
        
    % If we are doing calibration, get meter type from @Radiometer
    if (isa(obj.radiometerObj, 'Radiometer'))
        meterType = 0;
        if (strcmp(obj.radiometerObj.deviceModelName, 'PR-650'))
            meterType = 1;
        elseif (strcmp(obj.radiometerObj.deviceModelName, 'PR-655'))
            meterType = 4;
        elseif (strcmp(obj.radiometerObj.deviceModelName, 'PR-670'))
            meterType = 5;    
        end 
        oldFormatCalStruct.describe.whichMeterType = meterType;
    end
    
    oldFormatCalStruct.describe.HDRProjector  = 0;
    oldFormatCalStruct.describe.promptforname = 1;
    oldFormatCalStruct.describe.isExportedFromNewStyleCalStruct = 1; % new field to indicate that this has been exported from new style cal format
    oldFormatCalStruct.describe.newStyleCalStructRevisionNo = obj.calStructRevisionNo;
                            
end

