% Method to transform a calStruct generated by @Calibrator to a calStruct
% with the old-style format (expected by old-style calibration routines).
%
% Usage:
% oldFormatCalStruct = Calibrator.calStructWithOldFormat(newFormatCalStruct);
% 
% 4/16/2014   npc   Wrote it.
%

function oldFormatCalStruct = calStructWithOldFormat(obj, newFormatCalStruct)
% oldFormatCalStruct = calStructWithOldFormat(newFormatCalStruct)
%
% Description:
% Method to transform a calStruct generated by @Calibrator to a calStruct
% with the old-style format.
%
% Output:
% calStruct - A cal struct compatible with that expected from the old PsyCal functions

    [calStructOBJ, ~] = ObjectToHandleCalOrCalStruct(newFormatCalStruct);
    oldFormatCalStruct = calStructOBJ.cal;
    clear 'calStructOBJ'
end

