function validatedRotation = GLW_ValidateRotation(desiredRotation, displayTypeID)
% GLW_ValidateRotation - Validates rotation parameters.
%
% Syntax:
% validatedRotation = GLW_ValidateRotation(desiredRotation, displayTypeID)
%
% Description:
% Validates rotation parameters.  A single rotation value is a 1x4 vector
% consisting of a rotation amount in degrees and a 3 element (x,y,z) axis of
% rotation.  Rotation is always counterclockwise to the axis of rotation.
% Ex. [25 0 1 0] would mean a 25 degree CCW rotation about the y axis.
%
% Input:
% desiredRotation (Mx4) - Angle in degrees and axis of rotation. (angle, x, y, z)
% displayTypeID (integer) - The desired display ID type of the GLWindow.
%     This value should be generated by GLWindow.validateDisplayType.
%
% Output:
% validatedRotation (Mx4) - The validated rotation(s).

% Note:
% At one time there was interest in passing a different rotation parameter
% for each display of the GLWindow, but in the end that never happened.
% You'll notice the 'allowableRows' parameter that is essentially useless.
% I've kept it in just in case, but it's probably safe to get rid of.

switch displayTypeID
	case {GLWindow.DisplayTypes.Normal, GLWindow.DisplayTypes.BitsPP}
		if ~isnumeric(desiredRotation)
			error('"desiredRotation" must be a 1x4 array in Normal or BitsPP modes.');
		end
		
		allowableRows = 1;
		
	case {GLWindow.DisplayTypes.Stereo, GLWindow.DisplayTypes.StereoBitsPP}
		if ~isnumeric(desiredRotation)
			error('"desiredRotation" must be a 1x4 array in Stereo or StereoBitsPP modes.');
		end
		
		allowableRows = 1;
        
    case {GLWindow.DisplayTypes.HDR, GLWindow.DisplayTypes.StereoHDR}
		if ~isnumeric(desiredRotation)
			error('Rotation must be a 1x4 array in HDR or Stereo HDR modes.');
		end
		
		allowableRows = 1;
		
	otherwise
		error('Unsupported display type ID "%d".', displayTypeID);
end

if ~GLW_CheckDims(desiredRotation, {[allowableRows 4]})
	displayTypeName = GLWindow.displayTypeIDToName(displayTypeID);
	
	error('"desiredRotation" must be a %dx4 in %s mode.', allowableRows, displayTypeName);
end

validatedRotation = desiredRotation;
