function validatedDotSetColors = GLW_ValidateDotSetColors(desiredDotSetColors, displayTypeID)
% GLW_ValidateDotSetColors - Validates polygon set colors.
%
% Syntax:
% validatedDotSetColors = GLW_ValidateDotSetColors(desiredDotSetColors, displayTypeID)
%
% Description:
% Validates a set of colors for a dot set depending on the display type.
%
% Input:
% desiredDotSetColors (Mx3|cell array|struct) - The desired colors for
%	the dot set.
% displayTypeID (integer) - The display ID type of the GLWindow.
%   This value should be generated by GLW_ValidateDisplayType.
%
% Output:
% validatedDotSetColors (cell array) - The validated dot set colors
%   for each display in a cell array.

switch displayTypeID
	case {GLWindow.DisplayTypes.Normal, GLWindow.DisplayTypes.BitsPP}
		try
			checkMatrix(desiredDotSetColors);
			desiredDotSetColors = {desiredDotSetColors};
		catch e
			e.message = sprintf('In Normal or Bits++ mode, %s', e.message);
			rethrow(e);
		end
		
	case {GLWindow.DisplayTypes.Stereo, GLWindow.DisplayTypes.StereoBitsPP}
		if iscell(desiredDotSetColors)
			if length(desiredDotSetColors) ~= 2
				error('In Stereo or Stereo-Bits++ mode, cell arrays must only have 2 elements.');
			end
		elseif isstruct(desiredDotSetColors)
			% Validate the fields in the struct.
			GLW_ValidateStructFields(desiredDotSetColors, {'left', 'right'});
			
			desiredDotSetColors = {desiredDotSetColors.left, desiredDotSetColors.right};
		else
			error('In Stereo or Stereo-Bits++ mode, polygon set colors must be passed as a 1x2 cell array or struct.');
		end
		
		try
			for i = 1:2
				checkMatrix(desiredDotSetColors{i});
			end
		catch e
			e.message = sprintf('In Stereo or Stereo-Bits++ mode, all %s', e.message);
			rethrow(e);
		end
		
	case GLWindow.DisplayTypes.HDR
		if iscell(desiredDotSetColors)
			if length(desiredDotSetColors) ~= 2
				error('In HDR mode, cell arrays must only have 2 elements.');
			end
		elseif isstruct(desiredDotSetColors)
			% Validate the fields in the struct.
			GLW_ValidateStructFields(desiredDotSetColors, {'front', 'back'});
			
			desiredDotSetColors = {desiredDotSetColors.front, desiredDotSetColors.back};
		else
			error('In HDR mode, polygon set colors must be passed as a 1x2 cell array or struct.');
		end
		
		try
			for i = 1:2
				checkMatrix(desiredDotSetColors{i});
			end
		catch e
			e.message = sprintf('In HDR mode, all %s', e.message);
			rethrow(e);
		end
		
	otherwise
		error('Unknown display type ID of %d.', displayTypeID);
end

validatedDotSetColors = desiredDotSetColors;


function checkMatrix(m)
if ~isnumeric(m)
	error('dot set matrices must be numeric.');
end

if ndims(m) ~= 2
	error('dot set matrices must have 2 dimensions.');
end

if size(m, 2) ~= 3
	error('dot set matrices must be Mx3 in size.');
end
