function validatedWindowPosition = GLW_ValidateWindowPosition(desiredWindowPosition, displayTypeID)
% validatedWindowPosition = GLW_ValidateWindowPosition(desiredWindowPosition, displayTypeID)
%
% Description:
% Validates the desired window position of non-fullscreen windows depending
% on the display type.
%
% Input:
% desiredWindowPosition (Mx2|[]) - The desired window positions in pixels.
%   [0,0] is the top left corner of the screen.
% displayTypeID (integer) - The desired display ID type of the GLWindow.
%   This value should be generated by GLWindow.validateDisplayType.
%
% Output:
% validatedWindowPosition (Mx2) - The validated window position(s).

switch displayTypeID
	case {GLWindow.DisplayTypes.Normal, GLWindow.DisplayTypes.BitsPP}
		if isempty(desiredWindowPosition)
			desiredWindowPosition = [0 0];
		end
		
	case {GLWindow.DisplayTypes.Stereo, GLWindow.DisplayTypes.StereoBitsPP}
		if isempty(desiredWindowPosition)
			desiredWindowPosition = [0 0 ; 0 375];
		end
		
	case GLWindow.DisplayTypes.HDR
		if isempty(desiredWindowPosition)
			desiredWindowPosition = [0 0 ; 0 375];
		end
		
	case GLWindow.DisplayTypes.StereoHDR
		if isempty(desiredWindowPosition)
			desiredWindowPosition = [0 0 ; 0 375 ; 500 0 ; 500 375];
		end
		
	otherwise
		error('Unsupported display type ID "%d".', displayTypeID);
end

validatedWindowPosition = desiredWindowPosition;
