function destinationCalStruct = CalStructSet(sourceCalStruct, targetFieldName, fieldValue)
% Function to set the value of a calStruct field for calStructs with the old
% format or for calStructs with the format generated by a @Calibrator object. 
% 
% 4/21/2014   npc   Wrote it.
%
    % Generate a replica of the source CalStruct
    destinationCalStruct = sourceCalStruct;

    % Find the path (within the calStruct) of the targetFieldName
    if (CalStructHasNewStyleFormat(sourceCalStruct))        
        fieldNameStructPath = FieldNameFullPathInNewCalStruct(sourceCalStruct, targetFieldName, '');
    else
        fieldNameStructPath = FieldNameFullPathInOldCalStruct(sourceCalStruct, targetFieldName, '');
    end
    
    % Update targetFieldName
    if isempty(fieldNameStructPath)
        % targetFieldName was not found in calStruct, so add it as a new field
        fprintf('>> Did not find field ''%s'' in CalStruct, so will add it at the root.\n', targetFieldName);
        eval(sprintf('destinationCalStruct.%s = fieldValue;', targetFieldName));
    else
        % targetFieldName was found in calStruct, so update its value
        eval(sprintf('destinationCalStruct.%s = fieldValue;', fieldNameStructPath));
    end    
end

