function value = CalStructGet(calStruct, oldStyleCalStructFieldName)
% Function to return the value of a calStruct field for calStructs with the old
% format or for calStructs with the format generated by a @Calibrator object. 
% 
% 4/21/2014   npc   Wrote it.
%
     
    if (CalStructHasNewStyleFormat(calStruct))        
        fieldNameStructPath = FieldNameFullPathInNewCalStructForOldStyleFieldName(oldStyleCalStructFieldName);
    else
        fieldNameStructPath = FieldNameFullPathInOldCalStruct(calStruct, oldStyleCalStructFieldName, ''); 
        calStruct
        sprintf('calStruct.%s', fieldNameStructPath)
    end
    
    
    value = eval(sprintf('calStruct.%s', fieldNameStructPath));
    
end



function fieldNameFullPath = FieldNameFullPathInNewCalStructForOldStyleFieldName(oldStyleCalTargetFieldname)
% Basically a look-up table of fieldnames: old-style calStuct -> new-style calStruct
%
%   ------------------ cal.describe ---------------------
    if strcmp(oldStyleCalTargetFieldname, 'nPrimaryBases')
        fieldNameFullPath = 'describe.primaryBasesNum';
        
    elseif strcmp(oldStyleCalTargetFieldname, 'nDevices')
        fieldNameFullPath = 'describe.displayPrimariesNum';
        
    elseif strcmp(oldStyleCalTargetFieldname, 'computer')
        fieldNameFullPath = 'describe.computerInfo';
        
    elseif strcmp(oldStyleCalTargetFieldname, 'whichScreen')
        fieldNameFullPath = 'describe.whichScreen';
        
    elseif strcmp(oldStyleCalTargetFieldname, 'monitor')
        fieldNameFullPath = 'describe.displayDeviceName';
        
    elseif strcmp(oldStyleCalTargetFieldname, 'driver')
        fieldNameFullPath = 'describe.driver';
        
    elseif strcmp(oldStyleCalTargetFieldname, 'dacsize')
        fieldNameFullPath = 'describe.dacsize';
        
    elseif strcmp(oldStyleCalTargetFieldname, 'hz')
        fieldNameFullPath = 'describe.hz';
    
    elseif strcmp(oldStyleCalTargetFieldname, 'who')
        fieldNameFullPath = 'describe.who';
    
    elseif strcmp(oldStyleCalTargetFieldname, 'date')
        fieldNameFullPath = 'describe.date';
        
    elseif strcmp(oldStyleCalTargetFieldname, 'program')
        fieldNameFullPath = 'describe.executiveScriptName';
    
    elseif strcmp(oldStyleCalTargetFieldname, 'comment')
        fieldNameFullPath = 'describe.comment';
        
    elseif strcmp(oldStyleCalTargetFieldname, 'nDevices')
        fieldNameFullPath = 'describe.displayPrimariesNum';
           
    elseif strcmp(oldStyleCalTargetFieldname, 'fitType')
        fieldNameFullPath = 'describe.gamma.fitType';
        
    elseif strcmp(oldStyleCalTargetFieldname, 'exponents')
        fieldNameFullPath = 'describe.gamma.exponents';
     
    % ------------------ cal.rawData ---------------------------
    
    elseif strcmp(oldStyleCalTargetFieldname, 'S')
        fieldNameFullPath = 'rawData.S';
    
    % ------------------ cal.processedData ---------------------
    
    elseif strcmp(oldStyleCalTargetFieldname, 'gammaTable')
        fieldNameFullPath = 'processedData.gammaTable';
        
    elseif strcmp(oldStyleCalTargetFieldname, 'gammaInput')
        fieldNameFullPath = 'processedData.gammaInput';
        
    elseif strcmp(oldStyleCalTargetFieldname, 'P_device')
        fieldNameFullPath = 'processedData.P_device';
        
    elseif strcmp(oldStyleCalTargetFieldname, 'T_device')
        fieldNameFullPath = 'processedData.T_device';
        
    elseif strcmp(oldStyleCalTargetFieldname, 'S_device')
        fieldNameFullPath = 'processedData.S_device';
        
    elseif strcmp(oldStyleCalTargetFieldname, 'P_ambient')
        fieldNameFullPath = 'processedData.P_ambient';
        
    elseif strcmp(oldStyleCalTargetFieldname, 'T_ambient')
        fieldNameFullPath = 'processedData.T_ambient';
        
    elseif strcmp(oldStyleCalTargetFieldname, 'S_ambient')
        fieldNameFullPath = 'processedData.S_ambient';
        
    elseif strcmp(oldStyleCalTargetFieldname, 'M_device_linear')
        fieldNameFullPath = 'processedData.M_device_linear';
        
    elseif strcmp(oldStyleCalTargetFieldname, 'ambient_linear')
        fieldNameFullPath = 'processedData.ambient_linear';

    else
        error('Could not find equivalent field in the new calStruct for the old calStruct.%s', oldStyleCalTargetFieldname);
    end
    
    fprintf('>>> CalStructGet(''%s'') <- (new-style) cal.%s\n', oldStyleCalTargetFieldname, fieldNameFullPath);
end
