% Method to find a fieldname's full path within a new-style calStruct
function fieldNameFullPath = FieldNameFullPathInNewCalStruct(calStruct, targetFieldName, previousFieldNameFullPath)
%    
    fieldNameFullPath = '';
    
    if (strcmp(targetFieldName, 'T_sensor') || ...
        strcmp(targetFieldName, 'S_sensor') || ...
        strcmp(targetFieldName, 'T_linear') || ...
        strcmp(targetFieldName, 'S_linear') || ...
        strcmp(targetFieldName, 'M_device_linear') || ...
        strcmp(targetFieldName, 'M_linear_device') || ...
        strcmp(targetFieldName, 'M_ambient_linear') || ...
        strcmp(targetFieldName, 'ambient_linear') ...
        )
        fieldNameFullPath = sprintf('%s.%s','processedData', targetFieldName);
    end
    
end
