% Method to find a fieldname's full path within a new-style calStruct
function fieldNameFullPath = FieldPathInNewCalStruct(calStruct, targetFieldName, previousFieldNameFullPath)
%    
    processedSubStructFieldNames = {'gammaTable'; ...
                                    'gammaInput'; ...
                                    'P_device'; ...
                                    'T_device'; ...
                                    'S_device'; ...
                                    'P_ambient'; ...
                                    'T_ambient'; ...
                                    'S_ambient'; ...
                                    'T_sensor'; ...
                                    'S_sensor'; ...
                                    'T_linear'; ...
                                    'S_linear'; ...
                                    'M_device_linear'; ...
                                    'M_linear_device'; ...
                                    'M_ambient_linear'; ...
                                    'ambient_linear'; ...
                                    'gammaMode'; ...
                                    'iGammaTable'; ...
                                    'monSVs' ...
                                    };
    
    describeSubStructFieldNames = { 'primaryBasesNum' ...
                                   };
                               
    rawDataSubStructFieldNames = { 'S', ...
                                   'gammaTable', ...
                                   };
                               
                               
    if (ismember(targetFieldName, processedSubStructFieldNames))
        fieldNameFullPath = sprintf('%s.%s','processedData', targetFieldName);
        
    elseif (ismember(targetFieldName, describeSubStructFieldNames))
        fieldNameFullPath = sprintf('%s.%s','describe', targetFieldName);
    
    elseif (ismember(targetFieldName, rawDataSubStructFieldNames))
        fieldNameFullPath = sprintf('%s.%s','rawData', targetFieldName);
        
    else
        fieldNameFullPath = '';
    end
    
end
