% BrainardLabToolbox/SpectralData
%
% Spectral data, PTB format.
%
% spd_D65Peter.mat       - Some estimate of D65 generated by Peter Delahunt.  I'm not quite sure
%                          why we would ever want to use this.
% spd_bearFruitGrayB     - Illuminant spd from the BearFruit hyperspectral image.  Not sure what the "B"
%                          at the end designates.
% sur_macbethPeter       - Macbeth color checker spectra as measured by Peter Delahunt.
% sur_macbethBabel       - Macbeth color checker spectra from the BabelColor website.
% T_xyzKleinK10A         - XYZ functions of the Klein 10-A colorimeter, provided by email to Manuel.
%                          The tabulations really do have some negative numbers.  Not sure if these
%                          are real.  They could be if the effective functions result from a linear 
%                          combination of some other set of all positive functions.
% T_xyzKleinCIE          - CIE 1931 XYZ functions sent by Klein.
% den_Hemoglobin         - Estimates of density of hemoglobin (average of
%                          oxy and deoxy hemoglobin)