function WriteAnovaTable(filename,t,titleStr)
% WriteAnovaTable(filename,t,[titleStr])
%
% Write out the anova table generated by anovan as tab delimited text.
%
% The title string is optional but can be helpful for saving what the
% Anova is.
%
% 5/27/11  dhb  Wrote it.
% 7/7/13   dhb  Add title string.

if (nargin < 3)
    titleStr = [];
end

if (~isempty(titleStr))
    fid = fopen(filename,'w');
    fprintf(fid,titleStr);
    fprintf(fid,'\n');
end

for i = 2:size(t,1)
    anovaStruct(i-1).Source = t{i,1};
    anovaStruct(i-1).VarType = t{i,8};
    anovaStruct(i-1).SumSq = sprintf('%0.2f',t{i,2});
    anovaStruct(i-1).df = t{i,3};
    anovaStruct(i-1).MeanSq = sprintf('%0.2f',t{i,5});
    anovaStruct(i-1).F = sprintf('%0.2f',t{i,6});
    anovaStruct(i-1).p = AnovaPToStr(t{i,7});
end

% Do the write
WriteStructsToText(fid,anovaStruct);

% File close
fclose(fid);